new file:   apel

diff --git a/.emacs.d/json-reformat/.travis.yml b/.emacs.d/json-reformat/.travis.yml
--- a/.emacs.d/json-reformat/.travis.yml
+++ b/.emacs.d/json-reformat/.travis.yml
@@ -1,19 +1,16 @@
 language: emacs-lisp
 env:
   matrix:
-    - EMACS=emacs23
-    - EMACS=emacs24
-    - EMACS=emacs-snapshot
+    - EMACS=emacs24        EMACS_PPA=ppa:cassou/emacs
+    - EMACS=emacs-snapshot EMACS_PPA=ppa:ubuntu-elisp/ppa
   global:
-    - CASK=$HOME/.cask/bin/cask
+    - PATH=$HOME/.cask/bin:$PATH
 before_install:
-  - sudo add-apt-repository -y ppa:cassou/emacs
+  - sudo add-apt-repository -y "$EMACS_PPA"
   - sudo apt-get update -qq
-  - sudo apt-get install -qq $EMACS
-  - if [ "$EMACS" = 'emacs-snapshot' ]; then
-      sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-gtk;
-    fi
-  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10
-        https://raw.github.com/cask/cask/master/go | python
+  - sudo apt-get install --force-yes -qq "$EMACS"
+  - sudo apt-get install --force-yes -qq "${EMACS}-el" || true # OK to fail
+  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10 https://raw.github.com/cask/cask/master/go | python
+  - cask install
 script:
-  make test
+  cask exec ert-runner
