modified:   vncserver

diff --git a/init.d/vncserver b/init.d/vncserver
--- a/init.d/vncserver
+++ b/init.d/vncserver
@@ -1,4 +1,4 @@
-#!/bin/sh -e
+#!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          vncserver
 # Required-Start:    networking
@@ -6,41 +6,50 @@
 # Default-Stop:      0 6
 ### END INIT INFO
 PATH="$PATH:/usr/X11R6/bin/"
+PIDFILE=/var/run/vncserver.pid
 
 # The Username:Group that will run VNC
 export USER="abelardo"
+HOME="/home/$USER"
 
 #${RUNAS}
 
 # The display that VNC will use
-DISPLAY="99"
+DISPLAY="2"
 
 # Color depth (between 8 and 32)
-DEPTH="16"
+DEPTH=16
 
 # The Desktop geometry to use.
 #GEOMETRY="<WIDTH>x<HEIGHT>"
-#GEOMETRY="800x600"
-#GEOMETRY="1024x768"
-#GEOMETRY="1280x1024"
-GEOMETRY=1900x1280
-
-# The name that the VNC Desktop will have.
-NAME="my-vnc-server"
-
+GEOMETRY="1900x1280"
 OPTIONS=" -depth ${DEPTH} -geometry ${GEOMETRY} :${DISPLAY}"
 
 . /lib/lsb/init-functions
 
 case "$1" in
 start)
-log_action_begin_msg "Starting vncserver for user '${USER}' on localhost:${DISPLAY}"
-su ${USER} -c "/usr/bin/tightvncserver ${OPTIONS}"
+echo "Starting vncserver for user '${USER}' on localhost:${DISPLAY}"
+start-stop-daemon --chuid $USER:$USER --start --pidfile $PIFILE --make-pidfile --exec /usr/bin/tightvncserver -- $OPTIONS
+e=$?
+if [ $e -eq 1 ]; then
+  echo "Server is already running."
+  return
+fi
+
+if [ $e -eq 255 ]; then
+  echo "Server couldn't start."
+  exit 1
+fi
+echo "[done]"
 ;;
 
 stop)
-log_action_begin_msg "Stoping vncserver for user '${USER}' on localhost:${DISPLAY}"
+echo "Stoping vncserver for user '${USER}' on localhost:${DISPLAY}"
 su ${USER} -c "/usr/bin/tightvncserver -kill :${DISPLAY}"
+rm -rf /tmp/.X11-unix/X2
+start-stop-daemon -Kq -R 10 -p $PIDFILE
+echo "[done]"
 ;;
 
 restart)
